name: Manual Trigger
on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Provide your name'
        required: true
        type: string
jobs:
  Print-Input-Name:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, ${{ inputs.name }}!"